# Generated by Django 3.1.3 on 2021-04-12 14:52

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_remove_basedata_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crossvalscore',
            name='baseData',
        ),
        migrations.RemoveField(
            model_name='meanscore',
            name='baseData',
        ),
        migrations.DeleteModel(
            name='PredResults',
        ),
        migrations.RemoveField(
            model_name='singlescore',
            name='baseData',
        ),
        migrations.AddField(
            model_name='basedata',
            name='data',
            field=picklefield.fields.PickledObjectField(default='SOME STRING', editable=False),
        ),
        migrations.DeleteModel(
            name='crossValScore',
        ),
        migrations.DeleteModel(
            name='meanScore',
        ),
        migrations.DeleteModel(
            name='singleScore',
        ),
    ]
