# Generated by Django 3.1.3 on 2021-04-13 06:43

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0008_hello'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossValModelNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='CrossValModelNames', max_length=30)),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
                ('baseData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CrossValModelNames', to='predict.basedata')),
            ],
        ),
        migrations.CreateModel(
            name='CrossValScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='CrossValScores', max_length=30)),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
                ('baseData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CrossValScores', to='predict.basedata')),
            ],
        ),
        migrations.RemoveField(
            model_name='hello',
            name='baseData',
        ),
        migrations.RemoveField(
            model_name='meanscore',
            name='baseData',
        ),
        migrations.RemoveField(
            model_name='singlescore',
            name='baseData',
        ),
        migrations.DeleteModel(
            name='crossValScore',
        ),
        migrations.DeleteModel(
            name='Hello',
        ),
        migrations.DeleteModel(
            name='meanScore',
        ),
        migrations.DeleteModel(
            name='singleScore',
        ),
    ]
