# Generated by Django 3.1.7 on 2021-04-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_basedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedata',
            name='url',
            field=models.CharField(default='Name of the item', max_length=30),
        ),
    ]
