# Generated by Django 3.1.3 on 2021-04-12 14:56

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0006_auto_20210412_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='singleScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='singleScore', max_length=30)),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
                ('baseData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singleScore', to='predict.basedata')),
            ],
        ),
        migrations.CreateModel(
            name='meanScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='meanScore', max_length=30)),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
                ('baseData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanScore', to='predict.basedata')),
            ],
        ),
        migrations.CreateModel(
            name='crossValScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='crossValScore', max_length=30)),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
                ('baseData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossValScore', to='predict.basedata')),
            ],
        ),
    ]
