# Generated by Django 3.1.3 on 2021-04-13 07:15

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0009_auto_20210413_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizedHyperParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='OptimizedHyperParameters', max_length=30)),
                ('optimizedScores', picklefield.fields.PickledObjectField(editable=False)),
                ('modelNames', picklefield.fields.PickledObjectField(editable=False)),
                ('bestSingle', picklefield.fields.PickledObjectField(editable=False)),
                ('baseData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OptimizedHyperParameters', to='predict.basedata')),
            ],
        ),
    ]
