# Generated by Django 3.1.3 on 2021-04-13 07:27

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0010_optimizedhyperparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorityVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='MajorityVote', max_length=30)),
                ('mvc_scores', picklefield.fields.PickledObjectField(editable=False)),
                ('baseData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MajorityVote', to='predict.basedata')),
            ],
        ),
    ]
