# Generated by Django 3.1.3 on 2021-04-13 08:03

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0011_majorityvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='CrossVal', max_length=30)),
                ('cv_scores', picklefield.fields.PickledObjectField(editable=False)),
                ('cv_names', picklefield.fields.PickledObjectField(editable=False)),
                ('dimRed', picklefield.fields.PickledObjectField(editable=False)),
                ('baseData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CrossVal', to='predict.basedata')),
            ],
        ),
        migrations.RemoveField(
            model_name='crossvalscores',
            name='baseData',
        ),
        migrations.DeleteModel(
            name='CrossValModelNames',
        ),
        migrations.DeleteModel(
            name='CrossValScores',
        ),
    ]
